on: 
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      email:
        required: true
        type: string
      branch:
        required: true
        type: string
      assignees:
        required: true
        type: string
    secrets:
      MY_GITHUB_TOKEN:
        required: true

jobs:
  custom_test:
    name: go-update
    env:
      CGO_ENABLED: 0
      GIT_AUTHOR_NAME: ${{ inputs.username }}
      GIT_AUTHOR_EMAIL: ${{ inputs.email }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Cleanup Workspace
        if: ${{ always() }}
        run: |
          if [[ -d ${GITHUB_WORKSPACE} ]]; then shopt -s dotglob ; sudo rm -rf ${GITHUB_WORKSPACE}/* ; fi

      - name: Checkout
        uses: actions/checkout@v3

      # - uses: peterjgrainger/action-create-branch@v2.0.1
      #   env:
      #     MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      #   with:
      #     branch: 'update-v2'

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: install go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: bash
        run: |
          go mod tidy
          go get -modfile=go.mod -d -d -u -t ./...
          go mod tidy

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          commit-message: upgrade go mods
          title: ${{ inputs.branch }}
          assignees: ${{ inputs.assignees }}
          branch: ${{ inputs.branch }}
